#!/bin/bash
# Author : Maxime POUVREAU, Ben CALVET
# Script de Ban IP, à exécuter sur un routeur linux.
# Creative Commons, Tous droits réservés
# Lord Corp.
# Definition des variables :


if test -z $(dpkg -l | cut -f 3 -d " " | grep dialog)  ; then 
	apt update
	apt install dialog
fi


if [ "$(id -u)" != 0 ] ; then
	dialog --msgbox "Merci de lancer ce programme en tant que root !" 0 0
	exit 1
fi

SaisieIP() {
	while true ; do
		exec 3>&1
		ip=$(dialog --inputbox "Saisissez une IP :" 0 0 2>&1 1>&3);
		exec 3>&-
		if [ -z $ip ] ; then break ; fi
		if [[ "$ip" =~ ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$ ]] ; then
			break
		else
			dialog --msgbox "Merci de renseigner une adresse IP valide" 0 0
		fi
	done
}

SaisieTemps() {
	exec 3>&1
	temps=$(dialog --inputbox "Saisissez le temps (Par défaut 1min) :" 0 0 2>&1 1>&3);
	exec 3>&-
	if [ -z $temps ] ; then temps="1" ; fi
}

while true ; do
	exec 3>&1
	choix=$(dialog --menu "Quelle fonction utiliser ?" 0 0 0 \
		"1" "BANNIR UNE IP TEMPORAIREMENT" \
		"2" "BANNIR UNE IP DEFINITIVEMENT" \
		"3" "DEBANNIR UNE IP" \
		"4" "DEBANNISSEMENT D'URGENCE" \
		"5" "LISTE DES IP BANNIES" \
		"6" "FERMER LE SCRIPT" 2>&1 1>&3)
	exec 3>&-

case $choix in
	"1")
	SaisieIP
	SaisieTemps
	;;
	"2")
	SaisieIP
	;;
	"6")
	clear
	exit
	;;
esac
if [ -n "$ip" ] ; then
bash fonctions/funcs.sh "$choix" "$ip" "$temps"
fi
done
